import requests
import json
r = requests.get('http://dataservice.accuweather.com/forecasts/v1/daily/1day/318251?apikey=86jsyP6MFGYksPKTTEQfMfZGfKxjz5F1')
json_data = r.text
#print(json_data)
j_load = json.loads(json_data)
Max_Fahrenheit =(j_load["DailyForecasts"][0]['Temperature']['Maximum']['Value'])
Max_Celsius = round((Max_Fahrenheit-32)/1.8,2)
Min_Fahrenheit =(j_load["DailyForecasts"][0]['Temperature']['Minimum']['Value'])
Min_Celsius = round((Max_Fahrenheit-32)/1.8,2)
print()
print('Good Morning! Date:',j_load["DailyForecasts"][0]['Date'],'and your daily weahter forecast is:')
print()
print('Max Temperature F:',j_load["DailyForecasts"][0]['Temperature']['Maximum']['Value'])
print()
print('Max Celsius:',Max_Celsius)
print()
print('Min Celsius:',Min_Celsius)
print()
print('Min Temperature F:',j_load["DailyForecasts"][0]['Temperature']['Minimum']['Value'])
print()
print('Day:',j_load["DailyForecasts"][0]['Day']['IconPhrase'])
print()
print('Night:',j_load["DailyForecasts"][0]['Night']['IconPhrase'])
print()
print('Condition:',j_load["Headline"]['Category'])